

FROM swr.cn-north-4.myhuaweicloud.com/ascend-mindx/mindxrec_arm:pt2100_openEuler22_arm_20260815_143408
ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir -p /opt/buildtools && \
    cd /opt/buildtools && \
    wget --no-check-certificate https://pytorch-package.obs.cn-north-4.myhuaweicloud.com/pta/tools/obsutil_linux_arm64.tar.gz && \
    tar -zxvf obsutil_linux_arm64.tar.gz && \
    # 此时解压出来 /opt/buildtools/obsutil_linux_arm64_5.5.9
    ln -sf /opt/buildtools/obsutil_linux_arm64_5.5.9/obsutil /usr/bin/obsutil && \
    # 增加校验，构建阶段直接检测，失败直接终止镜像构建
    ls -l /usr/bin/obsutil && \
    /usr/bin/obsutil version
USER root